package com.ticketing.file;

import java.util.Optional;
import java.util.UUID;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ticketing.shared.api.ApiException;
import com.ticketing.shared.api.ResourceNotFoundException;
import com.ticketing.shared.port.IdGenerator;

/** Authorises an upload: checks the request is allowed, records PENDING metadata, and signs the upload. */
@Service
class FileUploadService {

    private final FileAssetRepository files;
    private final Optional<ObjectStorage> storage;
    private final IdGenerator idGenerator;
    private final FileProperties properties;

    FileUploadService(FileAssetRepository files, Optional<ObjectStorage> storage,
            IdGenerator idGenerator, FileProperties properties) {
        this.files = files;
        this.storage = storage;
        this.idGenerator = idGenerator;
        this.properties = properties;
    }

    @Transactional
    public UploadTicket requestUpload(UUID userId, FilePurpose purpose, String mime, long sizeBytes) {
        // resolved first so no metadata is written when uploads are not configured
        ObjectStorage provider = storage.orElseThrow(this::storageNotConfigured);
        validatePurpose(purpose);
        validateMime(mime);
        validateSize(purpose, sizeBytes);

        String folder = folderFor(purpose);
        String publicId = folder + "/" + idGenerator.newId(); // random key, never the original filename
        // a banner is linked to its event when attached, so no event is recorded here
        FileAsset asset = new FileAsset(idGenerator.newId(), userId, null, purpose, publicId, mime, sizeBytes);
        files.save(asset);
        return new UploadTicket(asset.getId(), provider.signUpload(publicId, folder));
    }

    /** Confirms the upload landed, re-checks its real type and size, and attaches it. Safe to call twice. */
    @Transactional
    public CompletedUpload complete(UUID userId, UUID fileId) {
        ObjectStorage provider = storage.orElseThrow(this::storageNotConfigured);
        FileAsset asset = files.findByIdAndOwnerUserId(fileId, userId).orElseThrow(ResourceNotFoundException::new);
        if (asset.isReady()) {
            return new CompletedUpload(asset, provider.imageUrl(asset.getPublicId())); // already done
        }
        if (asset.getStatus() != FileStatus.PENDING) {
            throw new ApiException(HttpStatus.CONFLICT, FileErrorCodes.INVALID_UPLOAD_REQUEST,
                    "This upload can no longer be completed.");
        }

        StoredObject stored = provider.find(asset.getPublicId())
                .orElseThrow(() -> new ApiException(HttpStatus.BAD_REQUEST, FileErrorCodes.UPLOAD_NOT_FOUND,
                        "No uploaded file was found for this request."));
        // trust the provider's report, not the values the client declared at request time
        validateMime(stored.mime());
        validateSize(asset.getPurpose(), stored.sizeBytes());
        asset.markReady(stored.mime(), stored.sizeBytes());
        return new CompletedUpload(asset, provider.imageUrl(asset.getPublicId()));
    }

    private void validatePurpose(FilePurpose purpose) {
        if (purpose == FilePurpose.EXPORT) {
            throw badRequest("Exports are generated by the system, not uploaded.");
        }
    }

    private void validateMime(String mime) {
        if (!properties.allowedMimeTypes().contains(mime)) {
            throw new ApiException(HttpStatus.UNSUPPORTED_MEDIA_TYPE, FileErrorCodes.UNSUPPORTED_FILE_TYPE,
                    "Only JPEG, PNG and WebP images are allowed.");
        }
    }

    private void validateSize(FilePurpose purpose, long sizeBytes) {
        long max = maxBytesFor(purpose);
        if (sizeBytes <= 0 || sizeBytes > max) {
            throw new ApiException(HttpStatus.PAYLOAD_TOO_LARGE, FileErrorCodes.FILE_TOO_LARGE,
                    "This file is larger than the allowed size.");
        }
    }

    private long maxBytesFor(FilePurpose purpose) {
        return (purpose == FilePurpose.EVENT_BANNER
                ? properties.bannerMaxSize() : properties.profileMaxSize()).toBytes();
    }

    private String folderFor(FilePurpose purpose) {
        return purpose == FilePurpose.EVENT_BANNER ? properties.bannerFolder() : properties.profileFolder();
    }

    private ApiException badRequest(String message) {
        return new ApiException(HttpStatus.BAD_REQUEST, FileErrorCodes.INVALID_UPLOAD_REQUEST, message);
    }

    private ApiException storageNotConfigured() {
        return new ApiException(HttpStatus.SERVICE_UNAVAILABLE, FileErrorCodes.STORAGE_NOT_CONFIGURED,
                "File uploads are not configured on this server.");
    }
}
