package com.ticketing.file;

import java.util.Optional;
import java.util.UUID;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.ticketing.event.EventService;
import com.ticketing.organizer.OrganizerProfileService;
import com.ticketing.shared.api.ApiException;
import com.ticketing.shared.port.IdGenerator;

/** Authorises an upload: checks the request is allowed, records PENDING metadata, and signs the upload. */
@Service
class FileUploadService {

    private final FileAssetRepository files;
    private final Optional<ObjectStorage> storage;
    private final EventService eventService;
    private final OrganizerProfileService organizerProfiles;
    private final IdGenerator idGenerator;
    private final FileProperties properties;

    FileUploadService(FileAssetRepository files, Optional<ObjectStorage> storage, EventService eventService,
            OrganizerProfileService organizerProfiles, IdGenerator idGenerator, FileProperties properties) {
        this.files = files;
        this.storage = storage;
        this.eventService = eventService;
        this.organizerProfiles = organizerProfiles;
        this.idGenerator = idGenerator;
        this.properties = properties;
    }

    @Transactional
    public UploadTicket requestUpload(UUID userId, FilePurpose purpose, UUID eventId, String mime, long sizeBytes) {
        // resolved first so no metadata is written when uploads are not configured
        ObjectStorage provider = storage.orElseThrow(() -> new ApiException(HttpStatus.SERVICE_UNAVAILABLE,
                FileErrorCodes.STORAGE_NOT_CONFIGURED, "File uploads are not configured on this server."));
        validatePurpose(purpose);
        validateMime(mime);
        validateSize(purpose, sizeBytes);
        UUID assetEventId = resolveEvent(userId, purpose, eventId);

        String folder = folderFor(purpose);
        String publicId = folder + "/" + idGenerator.newId(); // random key, never the original filename
        FileAsset asset = new FileAsset(idGenerator.newId(), userId, assetEventId, purpose, publicId, mime, sizeBytes);
        files.save(asset);
        return new UploadTicket(asset.getId(), provider.signUpload(publicId, folder));
    }

    private void validatePurpose(FilePurpose purpose) {
        if (purpose == FilePurpose.EXPORT) {
            throw badRequest("Exports are generated by the system, not uploaded.");
        }
    }

    private void validateMime(String mime) {
        if (!properties.allowedMimeTypes().contains(mime)) {
            throw new ApiException(HttpStatus.UNSUPPORTED_MEDIA_TYPE, FileErrorCodes.UNSUPPORTED_FILE_TYPE,
                    "Only JPEG, PNG and WebP images are allowed.");
        }
    }

    private void validateSize(FilePurpose purpose, long sizeBytes) {
        long max = maxBytesFor(purpose);
        if (sizeBytes <= 0 || sizeBytes > max) {
            throw new ApiException(HttpStatus.PAYLOAD_TOO_LARGE, FileErrorCodes.FILE_TOO_LARGE,
                    "This file is larger than the allowed size.");
        }
    }

    /** A banner belongs to an event the caller must own; a profile image belongs to the caller. */
    private UUID resolveEvent(UUID userId, FilePurpose purpose, UUID eventId) {
        if (purpose != FilePurpose.EVENT_BANNER) {
            return null;
        }
        if (eventId == null) {
            throw badRequest("A banner upload must name the event it is for.");
        }
        UUID organizerId = organizerProfiles.getByUser(userId).getId();
        eventService.getOwnedEvent(eventId, organizerId); // 404s if the caller does not own it
        return eventId;
    }

    private long maxBytesFor(FilePurpose purpose) {
        return (purpose == FilePurpose.EVENT_BANNER
                ? properties.bannerMaxSize() : properties.profileMaxSize()).toBytes();
    }

    private String folderFor(FilePurpose purpose) {
        return purpose == FilePurpose.EVENT_BANNER ? properties.bannerFolder() : properties.profileFolder();
    }

    private ApiException badRequest(String message) {
        return new ApiException(HttpStatus.BAD_REQUEST, FileErrorCodes.INVALID_UPLOAD_REQUEST, message);
    }
}
